# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:stable

variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

build-master:
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --pull --cache-from $CONTAINER_IMAGE:latest -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build-tags:
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --pull --cache-from $CONTAINER_IMAGE:$CI_COMMIT_TAG -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  only:
    - tags

build-ref:
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --pull --cache-from $CONTAINER_IMAGE:latest -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - branches
