# Config version. Do not change this
config-version = "1.0"

bind = "0.0.0.0:25577"
motd = "&3A OKTW Galaxy"
show-max-players = 500
online-mode = true
player-info-forwarding-mode = "legacy"
forwarding-secret = "eXbg0mlzD7IC"
announce-forge = true

[servers]

[forced-hosts]

[advanced]
compression-threshold = 1024
compression-level = -1
login-ratelimit = 3000
connection-timeout = 5000q
read-timeout = 30000
proxy-protocol = false

[query]
enabled = false
port = 25577
map = "OKTW"
show-plugins = false